plugins {
    // see https://fabricmc.net/develop/ for new versions
    id 'fabric-loom' version '1.11-SNAPSHOT' apply false
    // see https://projects.neoforged.net/neoforged/moddevgradle for new versions
    id 'net.neoforged.moddev' version '2.0.115' apply false
}

// groovy
subprojects {
    repositories {
        mavenCentral()
    }

    afterEvaluate { proj ->
        if (proj.plugins.hasPlugin('java')) {
            proj.dependencies {
                annotationProcessor "systems.manifold:manifold-preprocessor:2025.1.27"
                compileOnly        "systems.manifold:manifold:2025.1.27"
            }

            proj.tasks.withType(JavaCompile).configureEach {
                options.compilerArgs += ["-Xplugin:Manifold"]
            }
        }
    }
}

project.ext.set("props", new Properties())
def mcVer = rootProject.minecraft.toString()
def propFile = mcVer in ['1.21.1', '1.21.2', '1.21.3', '1.21.4'] ? "1.21" : mcVer
file("props/${propFile}.properties").withInputStream { project.props.load(it) }

println()
println "Minecraft: ${rootProject.minecraft} (Java ${project.props.java})"
println " Using Properties: props/${propFile}.properties"
println " - Parchment: ${project.props.parchment_mc} v${project.props.parchment_ver}"
println " - Forge: ${project.props.forge_ver}"
println " - NeoForm: ${project.props.neo_form_ver}"
println " - NeoForge: ${project.props.neoforge_ver}"
println()

def parseVersion = { String v -> v.tokenize('.').collect { it.isInteger() ? it.toInteger() : 0 } }
def cmpVersion = { List a, List b ->
    int len = Math.max(a.size(), b.size())
    for (int i = 0; i < len; i++) {
        int ai = i < a.size() ? a[i] : 0
        int bi = i < b.size() ? b[i] : 0
        if (ai < bi) return -1
        if (ai > bi) return 1
    }
    return 0
}

def currentVer = parseVersion(rootProject.minecraft.toString())
def targetVer = [1, 21, 9]
boolean isPreBelow119 = cmpVersion(currentVer, targetVer) < 0

def targetVer2 = [1, 21, 7]
boolean isPreBelow117 = cmpVersion(currentVer, targetVer2) < 0

def targetVer3 = [1, 21, 6]
boolean isPreBelow116 = cmpVersion(currentVer, targetVer3) < 0

def targetVer4 = [1, 21, 5]
boolean isPreBelow115 = cmpVersion(currentVer, targetVer4) < 0

def targetVer5 = [1, 21, 4]
boolean isPreBelow114 = cmpVersion(currentVer, targetVer5) < 0

def mcFlag = String.format("MC_%s=\n", rootProject.minecraft.replace(".", "_"))
def preFlag1 = isPreBelow119 ? "PRE_TYPED_ENTITY_DATA=\n" : ""
def preFlag2 = isPreBelow117 ? "PRE_WRITE_VIEW=\n" : ""
def preFlag3 = isPreBelow116 ? "PRE_PLAYER_LEVEL_METHOD=\n" : ""
def preFlag4 = isPreBelow115 ? "PRE_VILLAGERDATA_METHODS=\n" : ""
def preFlag5 = isPreBelow114 ? "PRE_CUSTOM_TEXTURES=\n" : ""
new File(projectDir, "build.properties").text = mcFlag + preFlag1 + preFlag2 + preFlag3 + preFlag4 + preFlag5
