# Important Notes:
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
version=1.4
group=live.gunnablescum.villagerpickup
java_version=25

# Common
minecraft_version=26.1
mod_name=Villager Pickup
mod_authors=["GunnableScum (Primary Maintainer)", "LivingLemming (Original Author)"]
mod_id=villagerpickup
license=CC0-1.0
credits=
description=Pick up and carry villagers with ease!
homepage_url=https://modrinth.com/mod/villager-pickup
source_url=https://github.com/Living-Lemming/Villager-Pickup-Mod/
minecraft_version_range=[26.1, 26.2)

# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21.10
parchment_version=2025.10.12

# Modloader Specific

# NeoForge (For porting, visit https://projects.neoforged.net/neoforged/neoform and https://projects.neoforged.net/neoforged/neoforge)
neo_form_version=26.1-1
neoforge_version=26.1.2.100

# Fabric (For porting, visit https://fabricmc.net/develop/)
fabric_version=0.145.1+26.1
fabric_loader_version=0.19.3

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
