# Important Notes:
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
version=1.2
group=live.gunnablescum.villagerpickup
java_version=21

# Minecraft Version (This is default, overridden with -Pminecraft=VERSION)
minecraft=1.21.10

# Common
mod_name=Villager Pickup
mod_authors=["GunnableScum (Primary Maintainer)", "LivingLemming (Original Author)"]
mod_id=villagerpickup
license=CC0-1.0
credits=
description=Pick up and carry villagers with ease!
homepage_url=https://modrinth.com/mod/villager-pickup
source_url=https://github.com/Living-Lemming/Villager-Pickup-Mod/tree/main
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
fabric_loader_version=0.17.3

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
