# Java Version
java=21

# Parchment MC
parchment_mc=1.21.8
parchment_ver=2025.09.14

# Loader-Specific Stuff
neoforge_ver=21.8.47
neo_form_ver=1.21.8-20250717.133445

# Forge is to my knowledge unused right now but better be safe than sorry
forge_ver=58.1.0

# Version Ranges
forge_version_range=[58,)
neoforge_version_range=[4,)
minecraft_version_range=[1.21.8,1.22)