# Java Version
java=21

# Parchment MC
parchment_mc=1.21.1
parchment_ver=2024.11.17

# Loader-Specific Stuff
fabric_api=0.102.0
neoforge_ver=21.0.167
neo_form_ver=1.21-20240613.152323

# Forge is to my knowledge unused right now but better be safe than sorry
forge_ver=51.1.33

# Version Ranges
forge_version_range=[51,)
neoforge_version_range=[4,)
minecraft_version_range=[1.21,1.22)