# Java Version
java=21

# Parchment MC
parchment_mc=1.21.9
parchment_ver=2025.10.05

# Loader-Specific Stuff
fabric_api=0.134.0
neoforge_ver=21.9.16-beta
neo_form_ver=1.21.9-20250930.151910

# Forge is to my knowledge unused right now but better be safe than sorry
forge_ver=59.0.5

# Version Ranges
forge_version_range=[59,)
neoforge_version_range=[4,)