# Java Version
java=21

# Parchment MC
parchment_mc=1.21.9
parchment_ver=2025.10.05

# Loader-Specific Stuff
neoforge_ver=21.10.8-beta
neo_form_ver=1.21.10-20251010.172816

# Forge is to my knowledge unused right now but better be safe than sorry
forge_ver=60.0.3

# Version Ranges
forge_version_range=[60,)
neoforge_version_range=[4,)
minecraft_version_range=[1.21.10,1.22)