name: Build Mod from Source

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Environment Variables
        run: env

      - name: Checkout Repository
        uses: actions/checkout@v7
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v6
        with:
          distribution: "temurin"
          java-version: 21

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew clean build

      - name: Upload Fabric Artifact
        uses: actions/upload-artifact@v7
        with:
          name: Villager-Pickup-Mod-Fabric
          path: fabric/build/libs

      - name: Upload NeoForge Artifact
        uses: actions/upload-artifact@v7
        with:
          name: Villager-Pickup-Mod-NeoForge
          path: neoforge/build/libs